#!/usr/bin/env bash

# Diffusion preprocessing pipeline using MRtrix3, FreeSurfer amd FSL tools
# Based on template from https://betterdev.blog/minimal-safe-bash-script-template/

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

usage() {
  cat <<EOF
Usage: $(basename "${BASH_SOURCE[0]}") [-h] [--no-color] [-f] b sub ses

Process diffusion MRI data for a single-subject with MRtrix3 and FreeSurfer

Positional arguments:
b               BIDS project directory
sub             BIDS subject
ses             BIDS session

Optional arguments:
-h, --help      print help and exit
--no-color      don't colorize terminal output
-f, --force     force overwrite of output files

EOF
  exit
}

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
}

setup_colors() {
  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m'
  else
    NOFORMAT='' RED='' GREEN='' ORANGE=''
  fi
}

msg() {
  echo >&2 -e "${1-}"
}

die() {
  local msg=$1
  local code=${2-1} # default exit status 1
  msg "$msg"
  exit "$code"
}

parse_params() {
  force=0

  while :; do
    case "${1-}" in
    -h | --help) usage ;;
    --no-color) NO_COLOR=1 ;;
    -f | --force) force=1 ;; # example flag
    -?*) die "Unknown option: $1" ;;
    *) break ;;
    esac
    shift
  done

  args=("$@")

  # check required params and arguments
  [[ ${#args[@]} -ne 3 ]] && usage

  return 0
}

parse_params "$@"
setup_colors

if [ ${force} -eq 1 ]; then
  force_str="-force"
else
  force_str=""
fi

bids_proj_dir=$(realpath "${args[0]}")
bids_subject="${args[1]}"
bids_session="${args[2]}"

dwi_dir="${bids_proj_dir}"/sub-"${bids_subject}"/ses-"${bids_session}"/dwi
fmap_dir="${bids_proj_dir}"/sub-"${bids_subject}"/ses-"${bids_session}"/fmap
out_dir="${bids_proj_dir}"/derivatives/mrtrix3/sub-"${bids_subject}"/ses-"${bids_session}"/dwi

msg "${GREEN}Step 1. Make a directory to store the results${NOFORMAT}"
mkdir -p "${out_dir}"
cd "${out_dir}"

msg "${GREEN}Step 2. Convert data from NIfTI to mif format using mrconvert${NOFORMAT}"
mrconvert -coord 3 0 -fslgrad "${fmap_dir}"/sub-"${bids_subject}"_ses-"${bids_session}"_dir-AP_epi.bvec "${fmap_dir}"/sub-"${bids_subject}"_ses-"${bids_session}"_dir-AP_epi.bval -json_import "${fmap_dir}"/sub-"${bids_subject}"_ses-"${bids_session}"_dir-AP_epi.json "${fmap_dir}"/sub-"${bids_subject}"_ses-"${bids_session}"_dir-AP_epi.nii b0_AP.mif ${force_str}
mrconvert -fslgrad "${dwi_dir}"/sub-"${bids_subject}"_ses-"${bids_session}"_dir-PA_dwi.bvec "${dwi_dir}"/sub-"${bids_subject}"_ses-"${bids_session}"_dir-PA_dwi.bval -json_import "${dwi_dir}"/sub-"${bids_subject}"_ses-"${bids_session}"_dir-PA_dwi.json "${dwi_dir}"/sub-"${bids_subject}"_ses-"${bids_session}"_dir-PA_dwi.nii dwi_PA.mif ${force_str}

b0_bvals=$(mrinfo -shell_bvalues b0_AP.mif)
if [[ ${b0_bvals} -gt 10 ]]; then
  die "${RED}ERROR: b-value of b0_AP.mif is not 0, exiting${NOFORMAT}"
fi

b0_pe_dir=$(mrinfo b0_AP.mif -property PhaseEncodingDirection 2>&1)
if [[ ${b0_pe_dir} == *'no "PhaseEncodingDirection"'* ]]; then
  msg "${ORANGE}WARNING: Phase encoding direction not found in b0_AP.mif, check images in mrview${NOFORMAT}"
elif [[ ${b0_pe_dir} != "j-" ]]; then
  die "${RED}ERROR: Phase encoding direction of b0_AP.mif is not A>>P, exiting${NOFORMAT}"
fi

mrview -quiet -mode 2 -load b0_AP.mif -interpolation 0 &

num_bvals=$(mrinfo -shell_sizes dwi_PA.mif | wc -w)
if [[ "${num_bvals}" -lt 2 ]]; then
  die "${RED}ERROR: dwi_PA.mif does not include at least 2 b-values, exiting${NOFORMAT}"
fi

dwi_PA_b0_val=$(mrinfo -shell_bvalues dwi_PA.mif | cut -d " " -f1)
if [[ ${dwi_PA_b0_val} -gt 10 ]]; then
  die "${RED}ERROR: Lowest b-value of dwi_PA.mif is not 0, exiting${NOFORMAT}"
fi

dwi_pe_dir=$(mrinfo dwi_PA.mif -property PhaseEncodingDirection 2>&1)
if [[ ${dwi_pe_dir} == *'no "PhaseEncodingDirection"'* ]]; then
  msg "${ORANGE}WARNING: Phase encoding direction not found in dwi_PA.mif, check images in mrview${NOFORMAT}"
elif [[ ${dwi_pe_dir} != "j" ]]; then
  die "${RED}ERROR: Phase encoding direction of dwi_PA.mif is not P>>A, exiting${NOFORMAT}"
fi

mrview -quiet -mode 2 -load dwi_PA.mif -interpolation 0 &

msg "${GREEN}Step 3. Concatenate the P>>A and A>>P data using mrcat${NOFORMAT}"
mrcat dwi_PA.mif b0_AP.mif dwi.mif ${force_str}

msg "${GREEN}Step 4. Denoise the data using dwidenoise${NOFORMAT}"
dwidenoise dwi.mif dwi_denoise.mif ${force_str}
mrcalc dwi.mif dwi_denoise.mif -subtract dwi_denoise_res.mif ${force_str}
mrview -quiet -mode 2 -load dwi_denoise_res.mif -interpolation 0 -load dwi.mif  -interpolation 0 -load dwi_denoise.mif -interpolation 0 &

msg "${GREEN}Step 5. Remove the Gibbs ringing artefact with mrdegibbs${NOFORMAT}"
mrdegibbs dwi_denoise.mif dwi_degibbs.mif ${force_str}
mrcalc dwi_denoise.mif dwi_degibbs.mif -subtract dwi_degibbs_res.mif ${force_str}
mrview -quiet -mode 2 -load dwi_degibbs_res.mif -interpolation 0 -load dwi_denoise.mif  -interpolation 0 -load dwi_degibbs.mif -interpolation 0 &

msg "${GREEN}Step 6. Correct for susceptibility and eddy current induced distortions and subject movements with FSL topup and eddy using dwifslpreproc${NOFORMAT}"
dwiextract -bzero dwi_degibbs.mif b0_degibbs.mif ${force_str}
b0_vols=$(mrinfo -shell_sizes b0_degibbs.mif)
mrconvert b0_degibbs.mif -coord 3 $((b0_vols-2)):$((b0_vols-1)) b0_degibbs_PA_AP.mif ${force_str}
mrview -quiet -mode 2 -load b0_degibbs_PA_AP.mif -interpolation 0 &

dwi_PA_vols=$(mrinfo -size dwi_PA.mif | cut -d " " -f 4)
mrconvert dwi_degibbs.mif -coord 3 0:$((dwi_PA_vols-1)) dwi_degibbs_PA.mif ${force_str}

dwifslpreproc ${force_str} dwi_degibbs_PA.mif dwi_tu_eddy.mif -align_seepi -rpe_header -se_epi b0_degibbs_PA_AP.mif -eddyqc_all eddy_qc_results -nocleanup -eddy_options "--slm=linear --data_is_shelled --repol --cnr_maps"

mrview -quiet -mode 2 -load dwi_degibbs.mif -interpolation 0 -load dwi_tu_eddy.mif -interpolation 0 &

msg "${GREEN}Step 7. Estimate the response functions of white matter (WM), grey matter (GM) and cerebro-spinal fluid (CSF) for spherical deconvolution using dwi2response${NOFORMAT}"
dwi2response dhollander dwi_tu_eddy.mif response_wm.txt response_gm.txt response_csf.txt -voxels response_voxels.mif ${force_str}
mrview -quiet -mode 2 -load dwi_tu_eddy.mif -interpolation 0 -overlay.load response_voxels.mif -overlay.interpolation 0 &
shview response_wm.txt &
shview response_gm.txt &
shview response_csf.txt &

msg "${GREEN}Step 8. Create a brain mask with SynthStrip${NOFORMAT}"
dwiextract -bzero dwi_tu_eddy.mif - | mrconvert - -coord 3 0 b0_tu_eddy.nii ${force_str}
mri_synthstrip -i b0_tu_eddy.nii -m b0_tu_eddy_mask.nii.gz
mrconvert b0_tu_eddy_mask.nii.gz b0_tu_eddy_mask.mif ${force_str}
mrview -quiet -mode 2 -load b0_tu_eddy.nii -interpolation 0 -roi.load b0_tu_eddy_mask.mif -roi.opacity 0.6 &

msg "${GREEN}Step 9. Estimate the diffusion tensor with dwi2tensor${NOFORMAT}"
dwi2tensor -mask b0_tu_eddy_mask.mif dwi_tu_eddy.mif dt.mif ${force_str}

msg "${GREEN}Step 10. Calculate the fractional anisotropy (FA) and first eigenvector (EV) maps with tensor2metric${NOFORMAT}"
tensor2metric -mask b0_tu_eddy_mask.mif -fa fa.mif -vector ev.mif dt.mif ${force_str}
mrview -quiet -mode 2 -load fa.mif -interpolation 0 -load ev.mif -interpolation 0 -odf.load_tensor dt.mif &


